name: 'Upload to Google Drive'
description: 'Uploads a file or a folder to Google Drive'
author: 'Parichay Barpanda'
inputs: 
  credentials:
    description: 'Google Service Account credentials'
    required: true
  folder:
    description: 'Google Drive folder ID to upload the cv to'
    required: true
  target:
    description: 'Local path to the file/folder to upload'
    required: true
  name:
    description: 'Optional name for upload file (will default to cv.pdf if not supplied)'
    required: false
    default: null
outputs:
  link:
    description: 'A link to the Drive folder'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'  
  color: 'orange'
