name: 'Upload PDF to Google Drive'
description: 'Uploads a PDF file to Google Drive'
author: 'Parichay Barpanda'
inputs: 
  credentials:
    description: 'Google Service Account credentials'
    required: true
  folderId:
    description: 'Google Drive folder ID to upload the cv to'
    required: true
  target:
    description: 'Local path to the file/folder to upload'
    required: true
  filename:
    description: 'Optional name for upload file (will default to upload.pdf if not supplied)'
    required: false
    default: null
  overwrite:
    description: 'Optionally overwrite if file with same name exists or create new'
    required: false
    default: false
outputs:
  link:
    description: 'A link to the Drive folder'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload'  
  color: 'blue'
